<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор страниц</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
</head>
<body>
<!-- Основная разметка страницы -->
<nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: bisque">
    <div class="container-fluid">

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li>
                    <a class="nav-link active" aria-current="page" href="/">Анализатор страниц</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/urls">Сайты</a>
                </li>

            </ul>

        </div>
    </div>
</nav>

<form action="/" method="post" style="margin-left: 200px; margin-right: 200px">
    <label for="exampleDataList" class="form-label">Бесплатно проверяйте сайты на SEO пригодность</label>
    <input class="form-control" list="datalistOptions" id="exampleDataList" type="text" name="url[name]"
           placeholder="https://forexample.ru">
    <?php if (isset($errors)): ?>
        <div style="color: red"><?= $errors ?></div>
    <?php endif ?>


    <input type="submit" class="btn btn-primary" value="ПРОВЕРИТЬ" />
</form>


<footer>

    <footer class="border-top py-3 mt-5 flex-shrink-0">
        <div class="container-lg">
            <div class="text-center">
                <a target="_blank">Produced by Oleg Ushkevich</a>
            </div>
        </div>
    </footer>
</body>


</html>
