<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор страниц</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
</head>
<body class="min-vh-100 d-flex flex-column">
<!-- Основная разметка страницы -->
<nav class="navbar navbar-expand-lg bg-body-tertiary " style="background-color: bisque">
    <div class="container-fluid">

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li>
                    <a class="nav-link active" aria-current="page" href="/">Анализатор страниц</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/urls">Сайты</a>
                </li>

            </ul>

        </div>
    </div>
</nav>

<div class="alert alert-<?= array_key_first($flash) ?>" role="alert">
    <?php if (count($flash) > 0) : ?>
        <ul>
            <?php foreach ($flash as $messages) : ?>
                <?php foreach ($messages as $message) : ?>
                    <?= $message ?>
                <?php endforeach ?>
            <?php endforeach ?>
        </ul>
    <?php endif ?>
</div>
<section style="margin-left: 100px; margin-right: 200px">
<h2> Сайт: <?= $url->getAddress() ?></h2>
<div class="table-responsive">
    <table class="table table-bordered table-hover text-nowrap" data-test="url">
        <tbody>
        <tr>
            <td>ID</td>
            <td><?= $url->getId() ?></td>
        </tr>
        <tr>
            <td>Имя</td>
            <td><?= $url->getAddress() ?></td>
        </tr>
        <tr>
            <td>Дата создания</td>
            <td><?= $url->getCreatedAt() ?></td>
        </tr>
        </tbody>
    </table>
</div>
<h2 class="mt-5 mb-3">Проверки</h2>
<form method="post" action="/urls/<?= $url->getId() ?>/checks">
    <input type="hidden" name="name" value="<?= $url->getAddress() ?>">
    <input type="submit" class="btn btn-primary" value="Запустить проверку">
</form>

<table class="table table-bordered table-hover" data-test="checks">
    <thead>
    <tr style="border: 2px; solid ; border-collapse: collapse; border-top: 2px solid; border-bottom: 2px solid">
        <th>ID</th>
        <th>Код ответа</th>
        <th>h1</th>
        <th>title</th>
        <th>description</th>
        <th>Дата создания</th>
    </tr>
    </thead>
    <?php
    if ($status === 'after check'): ?>
        <tbody>
        <?php foreach ($arrayUrlCheckObject as $check): ?>
            <tr style="border: 2px; solid ; border-collapse: collapse; border-top: 2px solid; border-bottom: 2px solid">
                <td class="text-break" style="white-space: nowrap"><?= $check->getId() ?></td>
                <td class="text-break"><?= $check->getStatusCod() ?></td>
                <td class="text-break"><?= $check->getH1() ?></td>
                <td class="text-break"><?= $check->getTitle() ?></td>
                <td class="text-break"><?= $check->getDescription() ?></td>
                <td class="text-break"><?= $check->getCreatedAt() ?></td>
            </tr>
            </tbody>
        <?php endforeach; ?>
    <?php endif ?>
</table>
 </section>
</body>
<?php ?>