<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Подключение Bootstrap</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: bisque">
    <div class="container-fluid">

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li>
                    <a class="nav-link active" aria-current="page" href="/">Анализатор страниц</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Сайты</a>
                </li>

            </ul>

        </div>
    </div>
</nav>
<section style="margin-left: 200px; margin-right: 200px">
<h2>Сайты</h2>
<table class="table table-bordered table-hover" data-test="urls">
    <thead>
    <tr style="border: 2px solid ; border-collapse: collapse; border-top: 2px solid ;">
        <th>ID</th>
        <th>Имя</th>
        <th>Последняя проверка</th>
        <th>Код ответа</th>

    </tr>
    </thead>
    <tbody>
    <?php foreach ($allUrlChecks as $check): ?>
    <tr style="border: 2px; solid ; border-collapse: collapse; border-top: 2px solid; border-bottom: 2px solid">
        <td><?= $check['url_id'] ?></td>
        <td><a href="/urls/<?= (int)$check['url_id'] ?>"> <?= $check['name'] ?></a></td>
        <td><?= $check['created_at'] ?></td>
        <td><?= $check['status_code'] ?></td>
    </tr>
    </tbody>
    <?php endforeach; ?>
</table>
</section>
</body>